### ISSUE TITLE
Naming of feature dimension in track dataset

### ISSUE THREAD

**Issue by deeplycloudy** [deeplycloudy/TRACER-PAWS-NEXRAD-LMA#9]
The feature dimension used in the split-merge script should be named `feature` instead of `features`.
https://github.com/deeplycloudy/TRACER-PAWS-NEXRAD-LMA/blob/a71c4faa5d8fa69928d9e3e6144a7fea968d05a4/scripts/Tracking/merge_split.py#L209

The rest of the feature-level variables in the track datasets have the dimension `feature`, so the `feature_parent_track_id` winds up floating on its own:
<img width="812" alt="image" src="https://user-images.githubusercontent.com/1325771/199533548-f0ef33da-b7d1-45d4-b4b5-94350c204c11.png">

Also, instead of hard-coding the feature and cell dimension names, you can read them from the [cell-level dataset](https://github.com/deeplycloudy/TRACER-PAWS-NEXRAD-LMA/blob/main/scripts/Tracking/knb_tobac_tracking.py#L602)
```
feature_dim = tobac_cell_ds.feature_id.dims[0]
cell_dim = tobac_cell_ds.cell_id.dims[0]
```
This also serves to confirm that the feature and cell ID variables are named as you expect - it will error if not.

Tagging @kelcyno.

**Comment by kelcyno** [comment]
This is updated in merge_split, all plurals are removed from the dimension names. Merge split will be removed when it is updated in tobac 1.4, until then I'm closing this issue and pushing the changes to the PAWS repository.
